import {Chip8} from './Chip8'
const chip8 = new Chip8()
chip8.register.stackPush(30)
chip8.register.stackPush(30)
chip8.register.stackPush(30)
chip8.register.stackPush(30)
chip8.register.stackPush(30)
chip8.register.stackPush(30)
chip8.register.stackPush(30)
chip8.register.stackPush(30)
chip8.register.stackPush(30)
chip8.register.stackPush(30)
chip8.register.stackPush(30)
chip8.register.stackPush(30)
chip8.register.stackPush(30)
chip8.register.stackPush(30)
chip8.register.stackPush(30)
chip8.register.stackPush(30)
const result = chip8.register.stackPop()
console.log(result)

